import React from 'react';
import { Navigate, useLocation } from 'react-router-dom';
import AdminDashboard from './AdminDashboard';
import ProfilAnggota from './ProfilAnggota';
import AdminUsers from './AdminUsers';
import AdminAbsensi from './AdminAbsensi';
import AdminBerita from './AdminBerita';
import AdminMatch from './AdminMatch';
import AdminRanking from './AdminRanking';
import AdminGallery from './AdminGallery';
import AdminContact from './AdminContact';
import AdminLaporan from './AdminLaporan';
import AdminLogs from './AdminLogs';
import AdminTampilan from './AdminTampilan';
import AdminPopup from './AdminPopup';
import AdminFooter from './AdminFooter';
import AdminSejarah from './AdminSejarah';
import AdminVisiMisi from './AdminVisiMisi';
import AdminFasilitas from './AdminFasilitas';
import AdminStructure from './AdminStructure';
import AdminProgram from './AdminProgram';
import AdminPrestasi from './AdminPrestasi';
import AdminFAQ from './AdminFAQ';
import AdminInventaris from './AdminInventaris';
import AdminRekapKeuangan from './AdminRekapKeuangan';
import AnalisisPerforma from './AnalisisPerforma';
import RaporAtlet from './RaporAtlet';
import LiveScoreWidget from './LiveScoreWidget';
import TestimonialUlasan from './TestimonialUlasan';
import TournamentLeague from './TournamentLeague';
import PwaApkManager from './PwaApkManager';
import FcmSettingsDashboard from './FcmSettingsDashboard';
import ManajemenDokumen from './ManajemenDokumen';
import ManajemenPoin from './ManajemenPoin';
import AuditLogPoin from './AuditLogPoin';
import KasManager from './KasManager';
import { KelolaSurat } from './KelolaSurat';
import KelolaNavbar from './KelolaNavbar';
import KelolaHero from './KelolaHero';
import JadwalLatihanView from './JadwalLatihanView';
import PublicKasView from './PublicKasView';
import News from './News';
import Gallery from './Gallery';
import DokumenPenting from './DokumenPenting';
import PublicInventaris from './PublicInventaris';
import PublicFAQ from './PublicFAQ';
import PublicProgram from './PublicProgram';
import PublicPrestasi from './PublicPrestasi';
import Ranking from './Rankings';
import ManajemenPendaftaran from '../ManajemenPendaftaran';
import ManajemenAtlet from '../ManajemenAtlet';
import BadmintonQuiz from './BadmintonQuiz';
import SeededTurnamen from './SeededTurnamen';
import AdminPendaftaranTurnamen from './AdminPendaftaranTurnamen';

type Props = { session: any };

export default function AdminRouteView({ session }: Props) {
  const location = useLocation();
  const role = session?.user?.user_metadata?.role === 'anggota' ? 'anggota' : 'admin';
  const isAdmin = role === 'admin';
  const path = location.pathname.replace(/^\/admin\/?/, '').replace(/\/$/, '').toLowerCase();
  const render = (Component: React.ComponentType<any>) => <Component session={session} />;
  const adminOnly = (Component: React.ComponentType<any>) => isAdmin ? render(Component) : <Navigate to="/admin/dashboard" replace />;

  switch (path) {
    case '':
    case 'dashboard': return <AdminDashboard />;
    case 'profil': return render(ProfilAnggota);
    case 'notifications': return render(FcmSettingsDashboard);
    case 'pwa-apk': return render(PwaApkManager);
    case 'analisis-performa': return render(AnalisisPerforma);
    case 'rapor-atlet': return render(RaporAtlet);
    case 'live-score': return render(LiveScoreWidget);
    case 'testimoni': return render(TestimonialUlasan);
    case 'turnamen-liga': return render(TournamentLeague);
    case 'jadwal': return <JadwalLatihanView />;
    case 'ranking': return isAdmin ? render(AdminRanking) : <div className="p-4 md:p-8"><Ranking /></div>;
    case 'skor': return adminOnly(AdminMatch);
    case 'kas': return isAdmin ? render(KasManager) : <div className="p-4 md:p-8"><PublicKasView /></div>;
    case 'rekap-keuangan': return adminOnly(AdminRekapKeuangan);
    case 'berita': return isAdmin ? render(AdminBerita) : <div className="p-4 md:p-8"><News /></div>;
    case 'galeri': return isAdmin ? render(AdminGallery) : <div className="p-4 md:p-8"><Gallery /></div>;
    case 'dokumen': return isAdmin ? render(ManajemenDokumen) : <div className="p-4 md:p-8"><DokumenPenting /></div>;
    case 'program': return isAdmin ? render(AdminProgram) : <div className="p-4 md:p-8"><PublicProgram /></div>;
    case 'prestasi': return isAdmin ? render(AdminPrestasi) : <div className="p-4 md:p-8"><PublicPrestasi /></div>;
    case 'faq': return isAdmin ? render(AdminFAQ) : <div className="p-4 md:p-8"><PublicFAQ /></div>;
    case 'sejarah': return adminOnly(AdminSejarah);
    case 'visi-misi': return adminOnly(AdminVisiMisi);
    case 'fasilitas': return adminOnly(AdminFasilitas);
    case 'struktur': return adminOnly(AdminStructure);
    case 'inventaris': return isAdmin ? render(AdminInventaris) : <div className="p-4 md:p-8"><PublicInventaris /></div>;
    case 'users': return adminOnly(AdminUsers);
    case 'pendaftaran': return adminOnly(ManajemenPendaftaran);
    case 'pendaftaran-turnamen': return adminOnly(AdminPendaftaranTurnamen);
    case 'peserta-turnamen': return adminOnly(AdminPendaftaranTurnamen);
    case 'atlet': return adminOnly(ManajemenAtlet);
    case 'absensi': return adminOnly(AdminAbsensi);
    case 'poin': return adminOnly(ManajemenPoin);
    case 'audit-poin': return adminOnly(AuditLogPoin);
    case 'laporan': return adminOnly(AdminLaporan);
    case 'surat': return adminOnly(KelolaSurat);
    case 'logs': return adminOnly(AdminLogs);
    case 'tampilan': return adminOnly(AdminTampilan);
    case 'navbar': return adminOnly(KelolaNavbar);
    case 'hero': return adminOnly(KelolaHero);
    case 'popup': return adminOnly(AdminPopup);
    case 'footer': return adminOnly(AdminFooter);
    case 'kontak': return adminOnly(AdminContact);
    case 'seeded':
    case 'pendaftaran/seeded-peserta': return adminOnly(SeededTurnamen);
    case 'quiz': return <BadmintonQuiz />;
    default: return <Navigate to="/admin/dashboard" replace />;
  }
}
// Tournament registration management restored for the admin portal.
