import React, { useMemo, useState } from 'react';
import { createWorker } from 'tesseract.js';
import { supabase } from '../supabase';
import { broadcastDataChange } from '../utils/realtimeHelper';
import Swal from 'sweetalert2';
import { CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, FileCheck2, FileUp, Loader2, MapPin, ScanLine, Trophy, Users, Home } from 'lucide-react';
import { motion } from 'framer-motion';
import Navbar from './Navbar';
import { useNavigate } from 'react-router-dom';

const CATEGORIES = ['Ganda Putra AD/BC-/C+C Ajatappareng', 'Ganda Putra CC Lokal Parepare'];
const FEE = 150000;
const ADMIN_WA = '6289641676342';
const NIK_REGIONS: Record<string,string> = {
  '7311':'Kabupaten Barru — Wilayah Ajatappareng',
  '7314':'Kabupaten Sidenreng Rappang (Sidrap) — Wilayah Ajatappareng',
  '7315':'Kabupaten Pinrang — Wilayah Ajatappareng',
  '7316':'Kabupaten Enrekang — Wilayah Ajatappareng',
  '7372':'Kota Parepare — Wilayah Parepare',
};
const emptyForm={kategori:CATEGORIES[0],nama_pemain_1:'',nama_pemain_2:'',whatsapp:'',email:'',asal_pb:'',domisili:''};
const emptyIdentity={nik:'',foto:null as File|null,ktp:null as File|null,fotoPreview:'',ktpPreview:'',ocrStatus:'Belum dipindai',wilayah:''};
type Identity=typeof emptyIdentity;

function generateCode(){return `B162-${new Date().toISOString().slice(0,10).replace(/-/g,'')}-${Math.random().toString(36).slice(2,7).toUpperCase()}`;}
function normalizeNIK(text:string){return text.toUpperCase().replace(/[OQ]/g,'0').replace(/[IL]/g,'1').replace(/S/g,'5').replace(/B/g,'8').replace(/G/g,'6').replace(/[^0-9]/g,'');}
function findNIK(text:string){const raw=text.toUpperCase().replace(/[OQ]/g,'0').replace(/[IL]/g,'1').replace(/S/g,'5').replace(/B/g,'8').replace(/G/g,'6');const compact=raw.replace(/[^0-9]/g,'');if(compact.length===16)return compact;for(const m of raw.match(/\d[\d\s.-]{14,22}\d/g)||[]){const n=normalizeNIK(m);if(n.length===16)return n;}return '';}
function validateNIK(nik:string){if(!/^\d{16}$/.test(nik))return{valid:false,message:'NIK harus terdiri dari tepat 16 digit.'};const region=NIK_REGIONS[nik.slice(0,4)];if(!region)return{valid:false,message:`NIK ${nik} terdeteksi, tetapi kode wilayah ${nik.slice(0,4)} bukan wilayah Ajatappareng/Parepare yang diizinkan.`};return{valid:true,region};}

export default function PendaftaranTurnamen(){
  const navigate=useNavigate();
  const [step,setStep]=useState(1);const [form,setForm]=useState(emptyForm);const [players,setPlayers]=useState<[Identity,Identity]>([{...emptyIdentity},{...emptyIdentity}]);
  const [proof,setProof]=useState<File|null>(null);const [proofPreview,setProofPreview]=useState('');const [loading,setLoading]=useState(false);const [ocrLoading,setOcrLoading]=useState<[boolean,boolean]>([false,false]);const [success,setSuccess]=useState<{code:string}|null>(null);
  const selectedLabel=useMemo(()=>form.kategori===CATEGORIES[0]?'Ajatappareng':'Lokal Parepare',[form.kategori]);
  const update=(key:keyof typeof form,value:string)=>setForm(p=>({...p,[key]:value}));
  const updatePlayer=(idx:0|1,patch:Partial<Identity>)=>setPlayers(p=>p.map((x,i)=>i===idx?{...x,...patch}:x) as [Identity,Identity]);

  const scanKTP=async(idx:0|1,file:File)=>{
    if(!file.type.startsWith('image/'))return Swal.fire({icon:'error',title:'KTP harus berupa foto',text:'Unggah KTP dalam format JPG, PNG, atau WEBP agar sistem dapat membaca NIK secara otomatis.'});
    if(file.size>5*1024*1024)return Swal.fire({icon:'error',title:'File KTP terlalu besar',text:'Ukuran maksimal KTP adalah 5 MB.'});
    updatePlayer(idx,{ktp:file,ktpPreview:URL.createObjectURL(file),ocrStatus:'Membaca NIK...'});setOcrLoading(p=>p.map((v,i)=>i===idx) as [boolean,boolean]);
    try{const worker=await createWorker('eng');const result=await worker.recognize(file);await worker.terminate();const nik=findNIK(result.data.text);const check=validateNIK(nik);
      if(!nik){updatePlayer(idx,{nik:'',wilayah:'',ocrStatus:'NIK tidak terbaca — unggah ulang KTP yang jelas'});throw new Error('NIK 16 digit tidak terbaca. Pastikan seluruh KTP terlihat, tidak blur, tidak terpotong, dan pencahayaan cukup.');}
      if(!check.valid){updatePlayer(idx,{nik,wilayah:'',ocrStatus:'DITOLAK — wilayah tidak sesuai'});throw new Error(check.message);}
      updatePlayer(idx,{nik,wilayah:check.region||'',ocrStatus:'VALID — wilayah diizinkan'});
      Swal.fire({icon:'success',title:'KTP berhasil diverifikasi',html:`NIK terbaca: <b>${nik}</b><br><span>${check.region}</span>`,confirmButtonColor:'#2563eb'});
    }catch(err:any){Swal.fire({icon:'error',title:'Verifikasi KTP gagal',text:err?.message||'NIK tidak dapat diverifikasi. Silakan foto ulang KTP dengan lebih jelas.',confirmButtonColor:'#ef4444'});}finally{setOcrLoading(p=>p.map((v,i)=>i===idx?false:v) as [boolean,boolean]);}
  };
  const selectFoto=(idx:0|1,file:File|undefined)=>{if(!file)return;if(!file.type.startsWith('image/'))return Swal.fire({icon:'error',title:'Foto tidak valid',text:'Foto pemain harus berupa file gambar.'});if(file.size>5*1024*1024)return Swal.fire({icon:'error',title:'Foto terlalu besar',text:'Ukuran maksimal foto pemain 5 MB.'});updatePlayer(idx,{foto:file,fotoPreview:URL.createObjectURL(file)});};
  const selectProof=(file:File|undefined)=>{if(!file)return;if(file.size>5*1024*1024)return Swal.fire({icon:'error',title:'Bukti pembayaran terlalu besar',text:'Ukuran maksimal 5 MB.'});setProof(file);setProofPreview(file.type.startsWith('image/')?URL.createObjectURL(file):'');};
  const next=()=>{
    if(step===1&&(!form.nama_pemain_1.trim()||!form.nama_pemain_2.trim()||!form.whatsapp.trim()))return Swal.fire({icon:'warning',title:'Data pasangan belum lengkap',text:'Nama kedua pemain dan WhatsApp wajib diisi.'});
    if(step===2&&(!form.asal_pb.trim()||!form.domisili.trim()))return Swal.fire({icon:'warning',title:'Data tim belum lengkap',text:'Asal PB/Klub dan domisili wajib diisi.'});
    if(step===2){const missing=players.findIndex(p=>!p.foto||!p.ktp||!p.nik||!validateNIK(p.nik).valid);if(missing!==-1)return Swal.fire({icon:'error',title:`Dokumen Pemain ${missing+1} belum memenuhi syarat`,text:'Foto terbaru dan KTP wajib. NIK harus terbaca otomatis dan kode wilayah harus termasuk Ajatappareng/Parepare.'});}
    setStep(v=>Math.min(4,v+1));
  };
  const previous=()=>setStep(v=>Math.max(1,v-1));
  const submit=async()=>{
    if(!proof)return Swal.fire({icon:'warning',title:'Bukti pembayaran belum dipilih',text:'Unggah bukti pembayaran terlebih dahulu.'});
    const checks=players.map(p=>validateNIK(p.nik));if(players.some(p=>!p.foto||!p.ktp)||checks.some(c=>!c.valid))return Swal.fire({icon:'error',title:'Pendaftaran ditolak sistem',text:'Setiap pemain wajib memiliki foto terbaru + KTP yang terbaca dan NIK dari wilayah Ajatappareng/Parepare.'});
    setLoading(true);try{const code=generateCode();const uploadDoc=async(file:File,name:string)=>{const ext=file.name.split('.').pop()?.toLowerCase()||'jpg';const path=`pendaftaran/${code}/${name}.${ext}`;const{error}=await supabase.storage.from('turnamen-dokumen').upload(path,file,{upsert:false,contentType:file.type});if(error)throw new Error(`Upload ${name} gagal: ${error.message}`);return path;};
      const[foto1,ktp1,foto2,ktp2]=await Promise.all([uploadDoc(players[0].foto!,'foto-pemain-1'),uploadDoc(players[0].ktp!,'ktp-pemain-1'),uploadDoc(players[1].foto!,'foto-pemain-2'),uploadDoc(players[1].ktp!,'ktp-pemain-2')]);
      const ext=proof.name.split('.').pop()?.toLowerCase()||'jpg';const proofPath=`turnamen-bilibili-162/${code}.${ext}`;const{error:proofError}=await supabase.storage.from('uploads').upload(proofPath,proof,{upsert:false,contentType:proof.type});if(proofError)throw new Error(`Upload bukti pembayaran gagal: ${proofError.message}`);const proofUrl=supabase.storage.from('uploads').getPublicUrl(proofPath).data.publicUrl;
      const payload={kode_pendaftaran:code,nama_pemain_1:form.nama_pemain_1.trim().toUpperCase(),nama_pemain_2:form.nama_pemain_2.trim().toUpperCase(),whatsapp:form.whatsapp.trim(),email:form.email.trim().toLowerCase()||null,asal_pb:form.asal_pb.trim().toUpperCase(),domisili:form.domisili.trim().toUpperCase(),kategori:form.kategori,biaya_pendaftaran:FEE,status_pembayaran:'Menunggu Verifikasi',bukti_pembayaran_url:proofUrl,status_pendaftaran:'Pending',nik_pemain_1:players[0].nik,nik_pemain_2:players[1].nik,foto_pemain_1_url:foto1,foto_pemain_2_url:foto2,ktp_pemain_1_url:ktp1,ktp_pemain_2_url:ktp2,wilayah_nik_pemain_1:players[0].wilayah,wilayah_nik_pemain_2:players[1].wilayah,verifikasi_nik_status:'Valid',verifikasi_nik_detail:`P1: ${players[0].wilayah}; P2: ${players[1].wilayah}`};
      const{error}=await supabase.from('pendaftaran_turnamen').insert(payload);if(error)throw error;broadcastDataChange('pendaftaran_turnamen','INSERT',payload);const wa=form.whatsapp.replace(/\D/g,'').replace(/^0/,'62')||ADMIN_WA;const message=encodeURIComponent(`*PENDAFTARAN BILIBILI 162 CUP I 2026*\n\nKode: *${code}*\nKategori: *${form.kategori}*\nPasangan: *${form.nama_pemain_1.toUpperCase()} & ${form.nama_pemain_2.toUpperCase()}*\nWilayah NIK P1: ${players[0].wilayah}\nWilayah NIK P2: ${players[1].wilayah}\nBiaya: *Rp150.000/pasang*\nStatus: *MENUNGGU VERIFIKASI ADMIN*\n\n09-12 September 2026\nGOR Titik Kumpul Soreang Parepare`);setSuccess({code});window.open(`https://wa.me/${wa}?text=${message}`,'_blank');
    }catch(err:any){Swal.fire({icon:'error',title:'Pendaftaran gagal',text:err?.message||'Data tidak berhasil disimpan. Silakan periksa kembali dokumen.'});}finally{setLoading(false);}
  };
  const goHome=()=>navigate('/');
  const onNavbarNavigate=(sectionId:string, subPath?:string)=>{const target=String(subPath||sectionId||'').toLowerCase().trim();if(!target||target==='home'||target==='beranda'){goHome();return;}navigate(`/${target}`);};
  if(success)return <div className="min-h-screen bg-[#0b0e14]"><Navbar onNavigate={onNavbarNavigate}/><main className="min-h-[calc(100dvh-5rem)] flex items-center justify-center px-4 py-8"><motion.div initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} className="w-full max-w-xl rounded-3xl border border-emerald-400/25 bg-slate-950/90 p-7 sm:p-9 shadow-2xl text-center"><div className="mx-auto mb-5 flex h-20 w-20 items-center justify-center rounded-3xl bg-emerald-500/15 text-emerald-400"><CheckCircle2 size={44}/></div><p className="text-[11px] font-black tracking-[.25em] text-emerald-400 uppercase">Pendaftaran Berhasil</p><h2 className="mt-2 text-2xl sm:text-3xl font-black text-white">BILIBILI 162 CUP I</h2><div className="mt-6 rounded-2xl border border-white/10 bg-white/[.03] p-5"><p className="text-xs text-slate-400 uppercase tracking-widest">Kode Pendaftaran</p><p className="mt-1 text-xl font-black text-amber-300 tracking-wider">{success.code}</p><p className="mt-4 text-xs leading-relaxed text-slate-300">KTP kedua pemain telah melewati pemeriksaan kode wilayah. Simpan kode pendaftaran untuk konfirmasi admin.</p></div><button onClick={()=>{setSuccess(null);setForm(emptyForm);setPlayers([{...emptyIdentity},{...emptyIdentity}]);setProof(null);setProofPreview('');setStep(1)}} className="mt-5 w-full rounded-xl bg-blue-600 px-4 py-3 text-xs font-black text-white uppercase tracking-wider">Daftar Pasangan Lain</button></motion.div></main></div>;
  return <div className="min-h-screen bg-[#0b0e14]"><Navbar onNavigate={onNavbarNavigate}/><main className="pt-16"><div className="mx-auto max-w-[1600px] px-3 sm:px-5 lg:px-8"><div className="mb-3 flex items-center justify-between gap-3"><button type="button" onClick={goHome} className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-slate-900/80 px-3.5 py-2 text-[11px] font-black uppercase tracking-wider text-slate-300 shadow-lg transition hover:border-blue-400/30 hover:text-white"><Home size={14}/> Beranda</button><span className="hidden sm:block text-[10px] font-bold uppercase tracking-[.18em] text-slate-500">Pendaftaran Turnamen • Bilibili 162 Cup I 2026</span></div><div className="w-full py-2 sm:py-5"><div className="relative overflow-hidden rounded-[28px] border border-blue-400/20 bg-gradient-to-br from-[#071225] via-[#0b1730] to-[#050a14] shadow-2xl"><div className="absolute inset-0 opacity-20 pointer-events-none" style={{backgroundImage:'radial-gradient(circle at 20% 10%, #2563eb 0, transparent 30%),radial-gradient(circle at 85% 20%, #f59e0b 0, transparent 28%)'}}/><div className="relative p-5 sm:p-8 lg:p-10"><div className="flex flex-col lg:flex-row lg:items-end lg:justify-between gap-5"><div><div className="inline-flex items-center gap-2 rounded-full border border-amber-400/20 bg-amber-400/10 px-3 py-1.5 text-[10px] font-black uppercase tracking-[.18em] text-amber-300"><Trophy size={13}/> Bilibili 162 Cup I • 2026</div><h1 className="mt-3 text-2xl sm:text-4xl font-black italic uppercase text-white">Pendaftaran Peserta</h1><p className="mt-2 max-w-2xl text-sm leading-relaxed text-slate-300">Foto terbaru dan KTP <b className="text-white">wajib untuk Pemain 1 dan Pemain 2</b>. Sistem membaca NIK pada KTP secara otomatis dan menolak pendaftaran apabila kode wilayah tidak termasuk Ajatappareng/Parepare.</p></div><div className="grid grid-cols-2 gap-2 sm:gap-3 shrink-0"><InfoBox icon={<CalendarDays size={18}/>} label="Pelaksanaan" value="09–12 Sep 2026"/><InfoBox icon={<MapPin size={18}/>} label="Lokasi" value="GOR Titik Kumpul Soreang Parepare"/></div></div>
  <div className="mt-7 grid grid-cols-4 gap-2 rounded-2xl border border-white/10 bg-black/20 p-2">{[['1','Pasangan'],['2','Identitas'],['3','Pembayaran'],['4','Konfirmasi']].map(([n,l])=><div key={n} className={`rounded-xl px-2 py-2 text-center ${step===Number(n)?'bg-blue-600 text-white':'text-slate-500'}`}><span className="text-[10px] font-black">{n}</span><p className="text-[9px] sm:text-[10px] font-bold uppercase tracking-wider">{l}</p></div>)}</div>
  {step===1&&<section className="mt-7 space-y-5"><div><label className="text-[11px] font-black uppercase tracking-widest text-slate-300">Kategori Pertandingan</label><select value={form.kategori} onChange={e=>update('kategori',e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 text-sm font-bold text-white outline-none"><option>{CATEGORIES[0]}</option><option>{CATEGORIES[1]}</option></select><p className="mt-2 text-xs text-slate-500">Kategori aktif: <span className="text-amber-300 font-bold">{selectedLabel}</span></p></div><div className="grid sm:grid-cols-2 gap-4"><Field label="Nama Pemain 1" value={form.nama_pemain_1} onChange={v=>update('nama_pemain_1',v)}/><Field label="Nama Pemain 2" value={form.nama_pemain_2} onChange={v=>update('nama_pemain_2',v)}/><Field label="WhatsApp Ketua/Penanggung Jawab" value={form.whatsapp} onChange={v=>update('whatsapp',v)} type="tel"/><Field label="Email (opsional)" value={form.email} onChange={v=>update('email',v)} type="email"/></div></section>}
  {step===2&&<section className="mt-7 space-y-6"><div className="grid sm:grid-cols-2 gap-4"><Field label="Asal PB / Klub" value={form.asal_pb} onChange={v=>update('asal_pb',v)}/><Field label="Kota / Domisili" value={form.domisili} onChange={v=>update('domisili',v)}/></div><div className="grid lg:grid-cols-2 gap-5"><PlayerIdentity index={0} identity={players[0]} ocrLoading={ocrLoading[0]} onPhoto={f=>selectFoto(0,f)} onKtp={f=>scanKTP(0,f)}/><PlayerIdentity index={1} identity={players[1]} ocrLoading={ocrLoading[1]} onPhoto={f=>selectFoto(1,f)} onKtp={f=>scanKTP(1,f)}/></div><div className="rounded-2xl border border-amber-400/20 bg-amber-400/5 p-4 text-xs text-slate-300"><b className="text-amber-300">Wilayah NIK yang diterima:</b> Barru, Sidrap, Pinrang, Enrekang, dan Kota Parepare. Sistem memeriksa 4 digit kode kabupaten/kota pada NIK, bukan sekadar nama domisili.</div></section>}
  {step===3&&<section className="mt-7 space-y-5"><div className="rounded-2xl border border-blue-400/15 bg-blue-500/5 p-5"><p className="text-[10px] font-black uppercase tracking-widest text-blue-300">Biaya Pendaftaran</p><p className="mt-1 text-3xl font-black text-amber-300">Rp150.000 <span className="text-xs text-slate-400">/ pasangan</span></p></div><label className="block"><span className="text-[11px] font-black uppercase tracking-widest text-slate-300">Bukti Pembayaran</span><span className="mt-2 flex min-h-36 cursor-pointer items-center justify-center rounded-2xl border border-dashed border-blue-400/30 bg-blue-500/5 p-5 text-center"><input type="file" accept="image/*,.pdf" className="hidden" onChange={e=>selectProof(e.target.files?.[0])}/>{proofPreview?<img src={proofPreview} className="h-24 w-24 rounded-xl object-cover border border-white/10"/>:<div><FileUp className="mx-auto text-blue-400" size={30}/><p className="mt-2 text-xs font-bold text-white">Pilih bukti transfer</p><p className="mt-1 text-[10px] text-slate-500">JPG/PNG/PDF • maksimal 5 MB</p></div>}</span></label></section>}
  {step===4&&<section className="mt-7 space-y-5"><div className="rounded-2xl border border-emerald-400/20 bg-emerald-500/5 p-5"><div className="flex items-center gap-2 text-emerald-300"><FileCheck2 size={20}/><p className="text-xs font-black uppercase tracking-widest">Pemeriksaan Akhir</p></div><div className="mt-4 grid sm:grid-cols-2 gap-3"><Summary label="Kategori" value={form.kategori}/><Summary label="Pasangan" value={`${form.nama_pemain_1.toUpperCase()} & ${form.nama_pemain_2.toUpperCase()}`}/><Summary label="NIK Pemain 1" value={`${players[0].nik} — ${players[0].wilayah}`}/><Summary label="NIK Pemain 2" value={`${players[1].nik} — ${players[1].wilayah}`}/></div></div><div className="rounded-2xl border border-white/10 bg-white/[.03] p-4 text-xs leading-relaxed text-slate-300"><b className="text-white">Persetujuan:</b> Saya memastikan data dan dokumen kedua pemain benar. Sistem akan menolak pendaftaran secara otomatis apabila NIK tidak terbaca, bukan 16 digit, atau kode wilayahnya di luar Ajatappareng/Parepare.</div></section>}
  <div className="mt-8 flex items-center justify-between gap-3 border-t border-white/10 pt-5"><button onClick={previous} disabled={step===1||loading} className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-xs font-black text-slate-300 disabled:opacity-30"><ChevronLeft size={15}/> Kembali</button>{step<4?<button onClick={next} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 text-xs font-black uppercase tracking-wider text-white">Lanjut <ChevronRight size={15}/></button>:<button onClick={submit} disabled={loading} className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-5 py-3 text-xs font-black uppercase tracking-wider text-white disabled:opacity-60">{loading?<><Loader2 size={15} className="animate-spin"/> Memproses...</>:<>Kirim Pendaftaran <CheckCircle2 size={15}/></>}</button>}</div><p className="mt-4 text-center text-[10px] text-slate-500">KTP disimpan pada penyimpanan dokumen privat dan hanya dapat diakses admin terautentikasi.</p></div></div></div></div></main></div>;
}
function PlayerIdentity({index,identity,ocrLoading,onPhoto,onKtp}:{index:number;identity:Identity;ocrLoading:boolean;onPhoto:(f:File|undefined)=>void;onKtp:(f:File)=>void}){return <div className="rounded-2xl border border-white/10 bg-slate-950/60 p-4"><div className="flex items-center gap-2"><Users size={18} className="text-blue-400"/><h3 className="text-sm font-black uppercase text-white">Pemain {index+1}</h3></div><div className="grid sm:grid-cols-2 gap-3 mt-4"><label className="cursor-pointer rounded-xl border border-dashed border-white/15 bg-white/[.03] p-4 text-center"><input type="file" accept="image/*" capture="user" className="hidden" onChange={e=>onPhoto(e.target.files?.[0])}/>{identity.fotoPreview?<img src={identity.fotoPreview} className="mx-auto h-28 w-24 rounded-xl object-cover"/>:<><ScanLine className="mx-auto text-blue-400" size={27}/><p className="mt-2 text-[10px] font-black uppercase text-white">Foto Terbaru *</p><p className="mt-1 text-[9px] text-slate-500">Bisa ambil langsung dari kamera</p></>}</label><label className="cursor-pointer rounded-xl border border-dashed border-white/15 bg-white/[.03] p-4 text-center"><input type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={e=>e.target.files?.[0]&&onKtp(e.target.files[0])}/>{identity.ktpPreview?<img src={identity.ktpPreview} className="mx-auto h-28 w-full rounded-xl object-cover"/>:<><FileUp className="mx-auto text-amber-400" size={27}/><p className="mt-2 text-[10px] font-black uppercase text-white">KTP *</p><p className="mt-1 text-[9px] text-slate-500">JPG/PNG/WEBP • maks. 5 MB</p></>}</label></div><div className="mt-3 rounded-xl border border-white/5 bg-white/[.02] p-3"><p className="text-[9px] uppercase tracking-widest text-slate-500">Hasil pembacaan NIK</p>{ocrLoading?<p className="mt-1 text-xs font-bold text-blue-300">Sedang membaca KTP...</p>:identity.nik?<><p className="mt-1 font-mono text-sm font-black text-white tracking-wider">{identity.nik}</p><p className={`mt-1 text-[10px] font-bold ${identity.wilayah?'text-emerald-300':'text-rose-300'}`}>{identity.ocrStatus}</p>{identity.wilayah&&<p className="mt-1 text-[10px] text-slate-400">{identity.wilayah}</p>}</>:<p className="mt-1 text-[10px] text-slate-500">Belum ada KTP yang dipindai.</p>}</div></div>}
function Field({label,value,onChange,type='text'}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label className="block"><span className="text-[11px] font-black uppercase tracking-widest text-slate-300">{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 text-sm text-white outline-none focus:border-blue-500"/></label>}
function InfoBox({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="rounded-2xl border border-white/10 bg-white/5 p-3"><div className="text-blue-400">{icon}</div><p className="mt-2 text-[9px] text-slate-400 uppercase">{label}</p><p className="text-xs font-black text-white">{value}</p></div>}
function Summary({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-white/10 bg-white/5 p-3"><p className="text-[9px] uppercase tracking-widest text-slate-500">{label}</p><p className="mt-1 text-xs font-bold text-white leading-relaxed">{value}</p></div>}
