import React,{useRef,useState} from 'react';
import {FileUp,Upload,FileSpreadsheet,FileDown,RefreshCw} from 'lucide-react';
import {supabase} from '../supabase';
import SeededTurnamen from './SeededTurnamen';
import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as pdfjsLib from 'pdfjs-dist';

const TOURNAMENT='TURNAMEN BADMINTON BILIBILI 162 CUP I TAHUN 2026';
const SHEETS=['PBSI - Seeded Utama & Sulsel','Seeded Putra (B-, C+, C-)','PBSI - Arsip Utama B & C','Seeded Putri (Database PBSI)'];
const k=(v:any)=>String(v??'').toLowerCase().trim().replace(/[^a-z0-9]+/g,' ');
const pick=(r:any,names:string[])=>{for(const n of names){const x=Object.entries(r).find(([a,b])=>k(a)===k(n)||k(a).includes(k(n)));if(x&&String(x[1]??'').trim())return x[1];}return null;};
function parseExcel(wb:XLSX.WorkBook){const out:any[]=[];for(const sheet of SHEETS){const ws=wb.Sheets[sheet];if(!ws)continue;const m=XLSX.utils.sheet_to_json<unknown[]>(ws,{header:1,defval:null,raw:true});const hi=m.findIndex(r=>Array.isArray(r)&&r.some(c=>k(c).includes('nama pemain')));if(hi<0)continue;const h=(m[hi] as any[]).map((x,i)=>String(x??'').trim()||`Kolom ${i+1}`);for(let i=hi+1;i<m.length;i++){const raw:any={};h.forEach((x,j)=>raw[x]=(m[i] as any[])?.[j]??null);const name=String(pick(raw,['Nama Pemain'])??'').trim();if(!name)continue;const no=Number(pick(raw,['No.','No']));const gender=sheet.includes('Putri')?'Putri':'Putra';const q=String(pick(raw,['Kualifikasi Turnamen Bilibili 162 Cup','Cakupan Kategori Turnamen'])??'').trim()||null;out.push({source_sheet:sheet,source_no:Number.isFinite(no)?no:null,player_name:name,club_name:String(pick(raw,['Klub / Asal PB'])??'').trim()||null,seeded_quality:String(pick(raw,['Kualitas Seeded'])??'').trim()||null,division_level:String(pick(raw,['Tingkat / Divisi'])??'').trim()||null,tournament_qualification:q,region_status:String(pick(raw,['Status Wilayah'])??'').trim()||null,validity_status:String(pick(raw,['Status Keabsahan'])??'').trim()||null,archive_category:String(pick(raw,['Arsip Database'])??'').trim()||null,gender,eligible_category:q||(gender==='Putri'?'Putri':null),raw_data:raw});}}return out;}
async function allPlayers(){const out:any[]=[];for(let from=0;;from+=1000){const {data,error}=await supabase.from('seeded_players').select('id,source_sheet,source_no,player_name,club_name,seeded_quality,division_level,tournament_qualification,region_status,validity_status,archive_category,gender,eligible_category,raw_data').order('source_sheet').order('source_no').range(from,from+999);if(error)throw error;out.push(...(data||[]));if((data||[]).length<1000)break;}return out;}
export default function SeededTurnamenIO(){const ex=useRef<HTMLInputElement>(null),pdf=useRef<HTMLInputElement>(null);const [busy,setBusy]=useState(false);const [msg,setMsg]=useState('');const runImport=async(rows:any[])=>{if(!rows.length)throw Error('Tidak ada data pemain valid.');const {data:t,error:te}=await supabase.from('seeded_tournaments').select('id').eq('name',TOURNAMENT).order('id',{ascending:false}).limit(1).maybeSingle();if(te)throw te;let tid=t?.id;if(!tid){const {data:c,error:e}=await supabase.from('seeded_tournaments').insert({name:TOURNAMENT,organizer:'Panitia Turnamen Badminton Bilibili 162 Cup I Tahun 2026',event_start:'2026-09-09',event_end:'2026-09-12',venue:'GOR Titik Kumpul Soreang Parepare'}).select('id').single();if(e)throw e;tid=c.id;}if(!confirm(`Sinkronkan ${rows.length.toLocaleString('id-ID')} data seeded ke Supabase?`))return;setBusy(true);try{const {data:last,error:me}=await supabase.from('seeded_players').select('id').order('id',{ascending:false}).limit(1).maybeSingle();if(me)throw me;const startId=(Number(last?.id)||0)+1;const {error:de}=await supabase.from('seeded_players').delete().eq('tournament_id',tid);if(de)throw de;for(let i=0;i<rows.length;i+=200){const batch=rows.slice(i,i+200).map((r,j)=>({...r,id:startId+i+j,tournament_id:tid}));const {error:e}=await supabase.from('seeded_players').insert(batch);if(e)throw e;}setMsg(`Berhasil mengimpor ${rows.length.toLocaleString('id-ID')} data.`);setTimeout(()=>location.reload(),500);}finally{setBusy(false);}};
const importExcel=async(f?:File)=>{if(!f)return;try{await runImport(parseExcel(XLSX.read(await f.arrayBuffer(),{type:'array'})));}catch(e:any){setMsg(`Gagal: ${e?.message||e}`)}finally{if(ex.current)ex.current.value='';}};
const exportExcel=async()=>{setBusy(true);try{const rows=await allPlayers();const wb=XLSX.utils.book_new();const ws=XLSX.utils.json_to_sheet(rows.map((p,i)=>({No:p.source_no??i+1,'Nama Pemain':p.player_name,'Klub / PB':p.club_name||'','Gender':p.gender||'','Kualitas Seeded':p.seeded_quality||'','Sumber':p.source_sheet,'Tingkat / Divisi':p.division_level||'','Kategori':p.eligible_category||'','Wilayah':p.region_status||'','Keabsahan':p.validity_status||'','Arsip':p.archive_category||''})));ws['!cols']=[{wch:7},{wch:28},{wch:25},{wch:10},{wch:16},{wch:34},{wch:22},{wch:34},{wch:24},{wch:22},{wch:30}];XLSX.utils.book_append_sheet(wb,ws,'Seeded Resmi');XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['TURNAMEN BADMINTON BILIBILI 162 CUP I TAHUN 2026'],['Total data',rows.length],['Sumber','Supabase / Seeded Resmi']]),'Informasi');XLSX.writeFile(wb,'Seeded_Resmi_Bilibili_162_Cup_I_2026.xlsx');}catch(e:any){setMsg(`Gagal export: ${e?.message||e}`)}finally{setBusy(false);}};
const exportPdf=async()=>{setBusy(true);try{const rows=await allPlayers();const d=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'});d.setFontSize(16);d.setFont('helvetica','bold');d.text('SEEDED RESMI BILIBILI 162',14,14);d.setFontSize(9);d.setFont('helvetica','normal');d.text('Turnamen Badminton Bilibili 162 Cup I Tahun 2026 • GOR Titik Kumpul Soreang Parepare',14,20);autoTable(d,{startY:25,head:[['No','Nama Pemain','Klub / PB','Gender','Seeded','Sumber','Kategori / Wilayah']],body:rows.map((p,i)=>[p.source_no??i+1,p.player_name,p.club_name||'-',p.gender||'-',p.seeded_quality||'-',p.source_sheet,p.region_status||p.eligible_category||p.archive_category||'-']),styles:{fontSize:7,cellPadding:2},headStyles:{fontSize:7,fontStyle:'bold'},alternateRowStyles:{fillColor:[245,247,250]},margin:{left:10,right:10}});d.save('Seeded_Resmi_Bilibili_162_Cup_I_2026.pdf');}catch(e:any){setMsg(`Gagal PDF: ${e?.message||e}`)}finally{setBusy(false);}};
const importPdf=async(f?:File)=>{if(!f)return;setBusy(true);try{const p=await pdfjsLib.getDocument({data:await f.arrayBuffer()}).promise;const rows:any[]=[];for(let n=1;n<=p.numPages;n++){const c=await (await p.getPage(n)).getTextContent();const g=new Map<number,string[]>();for(const it of c.items as any[]){const s=String(it.str??'').trim();if(!s)continue;const y=Math.round((it.transform?.[5]||0)/2)*2;const a=g.get(y)||[];a.push(s);g.set(y,a);}for(const a of g.values()){const s=a.join(' | '),m=s.match(/^\s*(\d+)\s*\|\s*(.*?)\s*\|\s*(.*?)\s*\|\s*(Putra|Putri)\s*\|\s*([^|]+)\s*\|\s*(.*?)\s*\|\s*(.*?)\s*$/i);if(m)rows.push({source_sheet:m[6],source_no:Number(m[1]),player_name:m[2],club_name:m[3],gender:m[4],seeded_quality:m[5],division_level:null,tournament_qualification:null,region_status:m[7],validity_status:null,archive_category:null,eligible_category:m[7],raw_data:{imported_from:'PDF'}});}}if(!rows.length)throw Error('PDF bukan format Seeded Resmi aplikasi. Gunakan PDF hasil export aplikasi atau Excel sumber.');await runImport(rows);}catch(e:any){setMsg(`Gagal PDF: ${e?.message||e}`)}finally{setBusy(false);if(pdf.current)pdf.current.value='';}};
return <div className="relative"><div className="sticky top-0 z-30 flex flex-wrap items-center justify-end gap-2 px-3 py-3 bg-[#050b17]/95 backdrop-blur border-b border-white/10"><input ref={ex} type="file" accept=".xlsx,.xls" className="hidden" onChange={e=>void importExcel(e.target.files?.[0])}/><input ref={pdf} type="file" accept=".pdf" className="hidden" onChange={e=>void importPdf(e.target.files?.[0])}/><button disabled={busy} onClick={()=>ex.current?.click()} className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-3 py-2 text-[10px] font-black uppercase disabled:opacity-50"><FileUp size={14}/> Import Excel</button><button disabled={busy} onClick={()=>pdf.current?.click()} className="inline-flex items-center gap-2 rounded-xl bg-rose-600 px-3 py-2 text-[10px] font-black uppercase disabled:opacity-50"><Upload size={14}/> Import PDF</button><button disabled={busy} onClick={()=>void exportExcel()} className="inline-flex items-center gap-2 rounded-xl bg-slate-800 border border-white/10 px-3 py-2 text-[10px] font-black uppercase disabled:opacity-50"><FileSpreadsheet size={14}/> Export Excel</button><button disabled={busy} onClick={()=>void exportPdf()} className="inline-flex items-center gap-2 rounded-xl bg-slate-800 border border-white/10 px-3 py-2 text-[10px] font-black uppercase disabled:opacity-50"><FileDown size={14}/> Export PDF</button><button disabled={busy} onClick={()=>location.reload()} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-3 py-2 text-[10px] font-black uppercase disabled:opacity-50"><RefreshCw size={14}/> Refresh</button>{msg&&<span className="basis-full text-right text-[10px] text-emerald-300">{msg}</span>}</div><SeededTurnamen/></div>;
}
